package io.searchbox.client;

/*Generated by MPS */

import javax.swing.JPanel;
import io.searchbox.client.config.HttpClientConfig;
import javax.swing.JTabbedPane;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import java.awt.FlowLayout;
import javax.swing.JTextField;
import java.awt.Dimension;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import org.elasticsearch.search.builder.SearchSourceBuilder;
import org.elasticsearch.index.query.QueryBuilders;
import io.searchbox.core.Search;
import io.searchbox.core.SearchResult;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class MainGui extends JPanel {

  private JestClientFactory factory;
  private JestClient client;

  public MainGui() {
    factory = new JestClientFactory();
    factory.setHttpClientConfig(new HttpClientConfig.Builder("http://localhost:9200").multiThreaded(true).build());
    client = factory.getObject();

    JTabbedPane jtb = new JTabbedPane();


    JPanel jplInnerPanel2 = createInnerSearchPanel();
    jtb.addTab("Search", jplInnerPanel2);



    jtb.setSelectedIndex(0);
    setLayout(new GridLayout(1, 1));
    add(jtb);


  }


  protected JPanel createInnerSearchPanel() {

    JPanel jplPanel = new JPanel();
    JLabel jlbDisplay = new JLabel("Search");
    JLabel jlbDisplay2 = new JLabel("Result");
    JTextArea jtaResult = new JTextArea();
    JPanel JPindex = new JPanel();
    JPindex.setLayout(new FlowLayout());


    JTextField jtfDocName = new JTextField();
    jtfDocName.setPreferredSize(new Dimension(500, 25));
    JButton searchBtn = new JButton("Search");

    searchBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent p0) {

        try {
          SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
          searchSourceBuilder.query(QueryBuilders.matchQuery(jtfDocName.getText(), "wanzi"));

          Search search = new Search.Builder(searchSourceBuilder.toString()).build();
          SearchResult result = client.execute(search);
          jtaResult.setText(result.getSourceAsString());



          System.out.println("Search document!!");
        } catch (IOException E) {
          System.out.println("Error in search document");
        }

      }
    });


    JPindex.add(jtfDocName);
    JPindex.add(searchBtn);


    jplPanel.setLayout(new BoxLayout(jplPanel, BoxLayout.Y_AXIS));
    jplPanel.add(jlbDisplay);

    jplPanel.add(JPindex);
    jplPanel.add(jlbDisplay2);
    jplPanel.add(jtaResult);

    return jplPanel;



  }

  public static void main(String[] args) {
    JFrame frame = new JFrame("Jest");
    frame.addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e) {
        System.exit(0);
      }
    });
    frame.getContentPane().add(new MainGui());
    frame.setSize(800, 600);
    frame.setVisible(true);
    System.out.println("Hello from tabb");
  }
}
